version: '3'

services:
  mariadb:
    image: mariadb:10.5.9
    container_name: mariadb
    # networks:
    #   - batch_network  
    ports:
      - 3306:3306    
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor1!
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=batchdb
      - MYSQL_USER=batch-app
      - MYSQL_PASSWORD=1q2w3e4r5t
      - TZ=Asia/Seoul
    volumes:
      - ./db/mariadb/conf.d:/etc/mysql/conf.d
      - ./db/mariadb/data:/var/lib/mysql
      - ./db/mariadb/initdb.d:/docker-entrypoint-initdb.d

  mongo1:
    image: mongo:4.4.5
    container_name: mongo1
    expose:
      - 27017
    ports:
      - 27017:27017      
    # networks:
    #   - batch_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "r0" ]
    volumes:
      - ./data/mongo-data:/var/lib/mongo/data

  mongo2:
    image: mongo:4.4.5
    container_name: mongo2
    expose:
      - 27018
    ports:
      - 27018:27017      
    # networks:
    #   - batch_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "r0" ]
    volumes:
      - ./data/mongo-data:/var/lib/mongo/data

  mongo3:
    image: mongo:4.4.5
    container_name: mongo3
    expose:
      - 27019
    ports:
      - 27019:27017      
    # networks:
    #   - batch_network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "r0" ]
    volumes:
      - ./data/mongo-data:/var/lib/mongo/data

#  oracle12c:
#    image: quay.io/maksymbilenko/oracle-12c
#    container_name: oracle12c
#    restart: always
#    ports:
#      - 1521:1521
#    environment:
#      USER: system
#      PASSWORD: oracle
#      DB_SID: xe
#      DB_SERVICE_NAME: xe
#    volumes:
#    - ./db/oracle/oradata:/opt/oracle/oradata
#    - ./db/oracle/initdb.d:/docker-entrypoint-initdb.d

#  oracle18c:
#    image: hothamandcheese/oracle-18.4.0-xe
#    container_name: oracle-18-xe
#    restart: always
#    ports:
#      - 1521:1521
#    environment:
#      - ORACLE_PWD=ORACLE
#      - ORACLE_CHARACTERSET=AL32UTF8
#    volumes:
#      - ./db/oracle/oradata:/opt/oracle/oradata
#      - ./db/oracle/initdb.d:/docker-entrypoint-initdb.d

#  mongoku:
#    image: huggingface/mongoku
#    container_name: mongoku
#    ports:
#      - 3100:3100
#    depends_on:
#      - mongo1
#      - mongo2
#      - mongo3
    # networks:
    #   - batch_network
#    environment:
#      MONGOKU_DEFAULT_HOST: "mongodb://mongo1:27017"