version: '3.9'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.11.6-ce.0'
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['time_zone'] = 'Asia/Seoul'
        ### GitLab NGINX Settings
        nginx['redirect_http_to_https'] = true
        nginx['redirect_http_to_https_port'] = 80
        nginx['ssl_ciphers'] = 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
        nginx['ssl_prefer_server_ciphers'] = 'off'
        nginx['ssl_protocols'] = 'TLSv1.2 TLSv1.3'
        ### Email Settings
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'jp1020@naver.com'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab Administrator'
      TZ: 'Asia/Seoul'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './volumes/config:/etc/gitlab'
      - './volumes/logs:/var/log/gitlab'
      - './volumes/data:/var/opt/gitlab'
      - '/etc/localtime:/etc/localtime:ro'
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '10'
  
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:v16.0.1'
    restart: always
    volumes:
      - './config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'      